import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
    
      <main className={styles.main}>
        

        <div className={styles.ImageWrap}>
        <img className={styles.myImg} src="/homeImg.jpg" ></img>
        </div>

        <h1 className={styles.title}>
        &lt;Hunting Coder/&gt;
        </h1>

        <div>
        <h2 className={styles.h2}>Latest blogs</h2>
          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p className={styles.p}>Javacript is Language used to design logictetur adipisicing elit. Assumenda, ducimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, esse.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p className={styles.p}>Javacript is Language used to design logicctetur adipisicing elit. Dolor, sit? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi, delectus.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p className={styles.p}>Javacript is Language used to design lectetur adipisicing elit. Debitis, corporis?x Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, quam.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
